import type { MenuItem, SiteData, Tap } from './types'

const tap = (
  n: number,
  name: string,
  style: string,
  brewery: string,
  origin: string,
  abv: number,
): Tap => ({ tap: n, name, style, brewery, origin, abv, on: true })

const item = (
  partial: Omit<MenuItem, 'available'> & { available?: boolean },
): MenuItem => ({
  available: true,
  ...partial,
})

export const DEFAULT_SITE_DATA: SiteData = {
  venue: {
    name: 'North Hanover Grille',
    shortName: 'N. Hanover Grille',
    phone: '(717) 241-5517',
    phoneHref: 'tel:+17172415517',
    address: '37 N. Hanover Street, Carlisle, PA 17013',
    mapsUrl: 'https://maps.google.com/?q=37+N+Hanover+St+Carlisle+PA+17013',
    facebookUrl: 'https://www.facebook.com/p/North-Hanover-Grille-100063744092978/',
    timezone: 'America/New_York',
  },
  hours: [
    { day: 0, label: 'Sunday', open: null, close: null },
    { day: 1, label: 'Monday', open: null, close: null },
    { day: 2, label: 'Tuesday', open: '11:00', close: '21:00' },
    { day: 3, label: 'Wednesday', open: '11:00', close: '21:00' },
    { day: 4, label: 'Thursday', open: '11:00', close: '21:00' },
    { day: 5, label: 'Friday', open: '11:00', close: '21:30' },
    { day: 6, label: 'Saturday', open: '11:00', close: '21:30' },
  ],
  taps: [
    tap(1, 'Yuengling Traditional Lager', 'Lager', 'D.G. Yuengling & Son', 'Pottsville, PA', 4.5),
    tap(2, 'Troegs Sunshine Pils', 'Pilsner', 'Tröegs Independent Brewing', 'Hershey, PA', 4.5),
    tap(3, 'Victory Prima Pils', 'Pilsner', 'Victory Brewing', 'Downingtown, PA', 5.3),
    tap(4, 'Troegs HopBack Amber', 'Amber', 'Tröegs Independent Brewing', 'Hershey, PA', 6.0),
    tap(5, 'Troegs Perpetual IPA', 'IPA', 'Tröegs Independent Brewing', 'Hershey, PA', 7.5),
    tap(6, 'Victory Golden Monkey', 'Belgian', 'Victory Brewing', 'Downingtown, PA', 9.5),
    tap(7, "Bell's Two Hearted", 'IPA', "Bell's Brewery", 'Comstock, MI', 7.0),
    tap(8, 'Sierra Nevada Pale Ale', 'Pale Ale', 'Sierra Nevada', 'Chico, CA', 5.6),
    tap(9, 'Guinness Draught', 'Stout', 'Guinness', 'Dublin, Ireland', 4.2),
    tap(10, 'Left Hand Milk Stout Nitro', 'Stout', 'Left Hand Brewing', 'Longmont, CO', 6.0),
    tap(11, 'Allagash White', 'Witbier', 'Allagash Brewing', 'Portland, ME', 5.1),
    tap(12, 'Dogfish Head 60 Minute', 'IPA', 'Dogfish Head', 'Milton, DE', 6.0),
    tap(13, 'Miller Lite', 'Lager', 'Miller Brewing', 'Milwaukee, WI', 4.2),
    tap(14, 'Seasonal Rotator', 'Seasonal', 'Ask your bartender', 'Rotating', 5.5),
  ],
  sauces: [
    'Mild',
    'Hot',
    'Fire',
    'Honey BBQ',
    'Hot Honey Garlic',
    'Sweet Heat Thai Chile',
    "General Tso's",
    'Smokey Reaper',
    'Black & Blue Garlic',
    'Honey Mustard',
    'Garlic Parm',
    'Mango Habanero',
    'Ranch Rub',
    'Garlic Romano Rub',
    'Old Bay Rub',
    'Cajun Rub',
    'Lemon Pepper',
  ],
  wingNotes:
    'Served with celery & bleu cheese or ranch. Extra dressing or celery $0.99 each.',
  menu: [
    item({
      id: 'wings-bone-in',
      category: 'wings',
      name: 'Bone-In Wings',
      description: 'Jumbo fresh wings, tossed in your choice of 17 sauces & dry rubs.',
      variants: [
        { id: '8', label: '8 pc', price: 11.99 },
        { id: '12', label: '12 pc', price: 15.99 },
        { id: '18', label: '18 pc', price: 21.99 },
      ],
    }),
    item({
      id: 'wings-boneless',
      category: 'wings',
      name: 'Boneless Wings',
      description: 'Crispy boneless wings. Tuesday 60¢ starting at 3 PM.',
      tags: ['Tuesday 60¢ from 3 PM'],
      variants: [
        { id: '8', label: '8 pc', price: 10.59 },
        { id: '12', label: '12 pc', price: 12.99 },
        { id: '18', label: '18 pc', price: 16.99 },
      ],
    }),
    item({
      id: 'crab-dip',
      category: 'starters',
      name: 'Crab Dip',
      description: 'Served with toasted baguettes & tortilla chips.',
      variants: [{ id: 'std', label: '', price: 12.99 }],
    }),
    item({
      id: 'spinach-artichoke',
      category: 'starters',
      name: 'Spinach Artichoke Dip',
      variants: [{ id: 'std', label: '', price: 9.99 }],
    }),
    item({
      id: 'mozzarella-moons',
      category: 'starters',
      name: 'Mozzarella Moons',
      description: 'With marinara sauce.',
      variants: [{ id: 'std', label: '', price: 8.59 }],
    }),
    item({
      id: 'stuffed-jalapenos',
      category: 'starters',
      name: 'Stuffed Jalapenos',
      variants: [{ id: 'std', label: '', price: 8.59 }],
    }),
    item({
      id: 'onion-rings',
      category: 'starters',
      name: 'Beer Battered Onion Rings',
      description: 'With petal sauce.',
      variants: [{ id: 'std', label: '', price: 7.99 }],
    }),
    item({
      id: 'potato-skins',
      category: 'starters',
      name: 'Potato Skins',
      description: 'Bacon & cheddar jack.',
      variants: [{ id: 'std', label: '', price: 8.99 }],
    }),
    item({
      id: 'macho-nachos',
      category: 'starters',
      name: 'Macho Nachos',
      description: 'Add chicken or beef +$3.59.',
      variants: [{ id: 'std', label: '', price: 10.99 }],
    }),
    item({
      id: 'quesadilla-cheese',
      category: 'quesadillas',
      name: 'Cheese Quesadilla',
      variants: [{ id: 'std', label: '', price: 9.59 }],
    }),
    item({
      id: 'quesadilla-chicken-beef',
      category: 'quesadillas',
      name: 'Chicken or Beef Quesadilla',
      variants: [{ id: 'std', label: '', price: 11.59 }],
    }),
    item({
      id: 'quesadilla-buffalo',
      category: 'quesadillas',
      name: 'Buffalo Chicken Quesadilla',
      variants: [{ id: 'std', label: '', price: 11.99 }],
    }),
    item({
      id: 'quesadilla-crab',
      category: 'quesadillas',
      name: 'Crab Quesadilla',
      variants: [{ id: 'std', label: '', price: 12.99 }],
    }),
    item({
      id: 'cream-of-crab',
      category: 'soups-salads',
      group: 'Soups',
      name: 'Cream of Crab',
      variants: [
        { id: 'cup', label: 'Cup', price: 5.99 },
        { id: 'bowl', label: 'Bowl', price: 7.59 },
      ],
    }),
    item({
      id: 'french-onion',
      category: 'soups-salads',
      group: 'Soups',
      name: 'French Onion Crock',
      variants: [{ id: 'std', label: '', price: 6.29 }],
    }),
    item({
      id: 'soup-du-jour',
      category: 'soups-salads',
      group: 'Soups',
      name: 'Soup du Jour',
      variants: [
        { id: 'cup', label: 'Cup', price: 4.99 },
        { id: 'bowl', label: 'Bowl', price: 5.99 },
      ],
    }),
    item({
      id: 'house-salad',
      category: 'soups-salads',
      group: 'Salads',
      name: 'NHG House Salad',
      variants: [
        { id: 'small', label: 'Small', price: 5.29 },
        { id: 'large', label: 'Large', price: 7.99 },
      ],
    }),
    item({
      id: 'caesar',
      category: 'soups-salads',
      group: 'Salads',
      name: 'Classic Caesar',
      variants: [
        { id: 'small', label: 'Small', price: 5.59 },
        { id: 'large', label: 'Large', price: 8.29 },
      ],
    }),
    item({
      id: 'greek-salad',
      category: 'soups-salads',
      group: 'Salads',
      name: 'Greek Salad',
      variants: [{ id: 'std', label: '', price: 9.99 }],
    }),
    item({
      id: 'cobb-salad',
      category: 'soups-salads',
      group: 'Salads',
      name: 'Steak or Chicken Cobb Salad',
      variants: [{ id: 'std', label: '', price: 12.99 }],
    }),
    item({
      id: 'chicken-salad',
      category: 'soups-salads',
      group: 'Salads',
      name: 'Crispy or Grilled Chicken Salad',
      variants: [{ id: 'std', label: '', price: 11.99 }],
    }),
    item({
      id: 'salad-addons',
      category: 'soups-salads',
      group: 'Add-ons',
      name: 'Salad Add-ons',
      description: 'Chicken, steak, salmon, or crab cake.',
      variants: [
        { id: 'chicken', label: 'Chicken', price: 4.99 },
        { id: 'steak', label: 'Steak', price: 6.99 },
        { id: 'salmon-crab', label: 'Salmon or Crab Cake', price: 7.99 },
      ],
    }),
    item({
      id: 'wrap-buffalo',
      category: 'handhelds',
      group: 'Specialty Wraps',
      name: 'Crispy Buffalo Chicken Wrap',
      description: 'Served with house kettle chips & pickle.',
      variants: [{ id: 'std', label: '', price: 8.99 }],
    }),
    item({
      id: 'wrap-caesar',
      category: 'handhelds',
      group: 'Specialty Wraps',
      name: 'Chicken Caesar Wrap',
      description: 'Served with house kettle chips & pickle.',
      variants: [{ id: 'std', label: '', price: 8.99 }],
    }),
    item({
      id: 'wrap-turkey',
      category: 'handhelds',
      group: 'Specialty Wraps',
      name: 'Turkey Bacon Cheddar Wrap',
      description: 'Served with house kettle chips & pickle.',
      variants: [{ id: 'std', label: '', price: 8.99 }],
    }),
    item({
      id: 'wrap-cheesesteak',
      category: 'handhelds',
      group: 'Specialty Wraps',
      name: 'Cheesesteak Wrap',
      description: 'Beef or chicken. Served with house kettle chips & pickle.',
      variants: [{ id: 'std', label: '', price: 8.99 }],
    }),
    item({
      id: 'wrap-california',
      category: 'handhelds',
      group: 'Specialty Wraps',
      name: 'California Club Wrap',
      description: 'Served with house kettle chips & pickle.',
      variants: [{ id: 'std', label: '', price: 8.99 }],
    }),
    item({
      id: 'wrap-veggie',
      category: 'handhelds',
      group: 'Specialty Wraps',
      name: 'Veggie & Hummus Wrap',
      description: 'Served with house kettle chips & pickle.',
      variants: [{ id: 'std', label: '', price: 8.99 }],
    }),
    item({
      id: 'sandwich-crab-cake',
      category: 'handhelds',
      group: 'Sandwiches & Melts',
      name: 'Crab Cake Sandwich',
      description: 'Served with house kettle chips & pickle.',
      variants: [{ id: 'std', label: '', price: 13.99 }],
    }),
    item({
      id: 'sandwich-reuben',
      category: 'handhelds',
      group: 'Sandwiches & Melts',
      name: 'Classic Reuben',
      description: 'Served with house kettle chips & pickle.',
      variants: [{ id: 'std', label: '', price: 10.99 }],
    }),
    item({
      id: 'sandwich-french-dip',
      category: 'handhelds',
      group: 'Sandwiches & Melts',
      name: 'French Dip Au Jus',
      description: 'Served with house kettle chips & pickle.',
      variants: [{ id: 'std', label: '', price: 10.99 }],
    }),
    item({
      id: 'sandwich-cheesesteak',
      category: 'handhelds',
      group: 'Sandwiches & Melts',
      name: 'Classic Cheesesteak',
      description: 'Beef or chicken. Served with house kettle chips & pickle.',
      variants: [{ id: 'std', label: '', price: 10.59 }],
    }),
    item({
      id: 'sandwich-rachel',
      category: 'handhelds',
      group: 'Sandwiches & Melts',
      name: 'Rachel Sandwich',
      description: 'Served with house kettle chips & pickle.',
      variants: [{ id: 'std', label: '', price: 10.99 }],
    }),
    item({
      id: 'sandwich-chicken',
      category: 'handhelds',
      group: 'Sandwiches & Melts',
      name: 'Grilled Chicken Breast Sandwich',
      description: 'Served with house kettle chips & pickle.',
      variants: [{ id: 'std', label: '', price: 9.99 }],
    }),
    item({
      id: 'burger-classic',
      category: 'handhelds',
      group: '1/2 lb Fresh Craft Burgers',
      name: 'Hanover Classic Burger',
      description: 'With chips & pickle. Sub fries +$1.99.',
      variants: [{ id: 'std', label: '', price: 9.99 }],
    }),
    item({
      id: 'burger-bacon-cheddar',
      category: 'handhelds',
      group: '1/2 lb Fresh Craft Burgers',
      name: 'Bacon Cheddar Burger',
      description: 'With chips & pickle. Sub fries +$1.99.',
      variants: [{ id: 'std', label: '', price: 10.99 }],
    }),
    item({
      id: 'burger-mushroom-swiss',
      category: 'handhelds',
      group: '1/2 lb Fresh Craft Burgers',
      name: 'Mushroom Swiss Burger',
      description: 'With chips & pickle. Sub fries +$1.99.',
      variants: [{ id: 'std', label: '', price: 10.99 }],
    }),
    item({
      id: 'burger-black-bleu',
      category: 'handhelds',
      group: '1/2 lb Fresh Craft Burgers',
      name: 'Black & Bleu Burger',
      description: 'With chips & pickle. Sub fries +$1.99.',
      variants: [{ id: 'std', label: '', price: 10.99 }],
    }),
    item({
      id: 'burger-rodeo',
      category: 'handhelds',
      group: '1/2 lb Fresh Craft Burgers',
      name: 'Rodeo BBQ Bacon Burger',
      description: 'With chips & pickle. Sub fries +$1.99.',
      variants: [{ id: 'std', label: '', price: 11.49 }],
    }),
    item({
      id: 'entree-twin-crab',
      category: 'entrees',
      name: 'Twin Jumbo Crab Cakes',
      description: 'Served with two sides.',
      variants: [{ id: 'std', label: '', price: 24.99 }],
    }),
    item({
      id: 'entree-single-crab',
      category: 'entrees',
      name: 'Single Crab Cake Dinner',
      description: 'Served with two sides.',
      variants: [{ id: 'std', label: '', price: 17.99 }],
    }),
    item({
      id: 'entree-salmon',
      category: 'entrees',
      name: 'Fresh Atlantic Salmon',
      description: 'Lemon Pepper, Cajun, or Bourbon Glazed. Served with two sides.',
      variants: [{ id: 'std', label: '', price: 18.99 }],
    }),
    item({
      id: 'entree-ny-strip',
      category: 'entrees',
      name: '10oz NY Strip Steak',
      description: 'Served with two sides.',
      variants: [{ id: 'std', label: '', price: 21.99 }],
    }),
    item({
      id: 'entree-fish-chips',
      category: 'entrees',
      name: 'Beer Battered Fish & Chips',
      description: 'Served with two sides.',
      variants: [{ id: 'std', label: '', price: 15.99 }],
    }),
    item({
      id: 'entree-alfredo',
      category: 'entrees',
      name: 'Fettuccine Alfredo',
      description: 'Add chicken +$4.99. Add shrimp or crab +$6.99.',
      variants: [{ id: 'std', label: '', price: 13.99 }],
    }),
    item({
      id: 'side-fries',
      category: 'sides',
      name: 'French Fries',
      variants: [{ id: 'std', label: '', price: 3.29 }],
    }),
    item({
      id: 'side-sweet-fries',
      category: 'sides',
      name: 'Sweet Potato Fries',
      variants: [{ id: 'std', label: '', price: 3.29 }],
    }),
    item({
      id: 'side-onion-rings',
      category: 'sides',
      name: 'Onion Rings',
      variants: [{ id: 'std', label: '', price: 3.29 }],
    }),
    item({
      id: 'side-chips',
      category: 'sides',
      name: 'House Kettle Chips',
      variants: [{ id: 'std', label: '', price: 3.29 }],
    }),
    item({
      id: 'side-slaw',
      category: 'sides',
      name: 'Cole Slaw',
      variants: [{ id: 'std', label: '', price: 3.29 }],
    }),
    item({
      id: 'side-broccoli',
      category: 'sides',
      name: 'Steamed Broccoli',
      variants: [{ id: 'std', label: '', price: 3.29 }],
    }),
    item({
      id: 'side-baked-potato',
      category: 'sides',
      name: 'Baked Potato',
      variants: [{ id: 'std', label: '', price: 3.29 }],
    }),
    item({
      id: 'side-applesauce',
      category: 'sides',
      name: 'Applesauce',
      variants: [{ id: 'std', label: '', price: 3.29 }],
    }),
    item({
      id: 'kids-tenders',
      category: 'kids',
      name: 'Chicken Tenders',
      description: 'Includes drink & fries or applesauce.',
      variants: [{ id: 'std', label: '', price: 6.99 }],
    }),
    item({
      id: 'kids-grilled-cheese',
      category: 'kids',
      name: 'Grilled Cheese',
      description: 'Includes drink & fries or applesauce.',
      variants: [{ id: 'std', label: '', price: 6.99 }],
    }),
    item({
      id: 'kids-mac',
      category: 'kids',
      name: 'Kraft Mac & Cheese',
      description: 'Includes drink & fries or applesauce.',
      variants: [{ id: 'std', label: '', price: 6.99 }],
    }),
    item({
      id: 'kids-slider',
      category: 'kids',
      name: 'Cheeseburger Slider',
      description: 'Includes drink & fries or applesauce.',
      variants: [{ id: 'std', label: '', price: 6.99 }],
    }),
  ],
  specials: {
    hasFlyer: false,
    updatedAt: null,
  },
  banquet: {
    capacity: 30,
    blurb:
      'Our private dining suite seats up to 30 guests — rehearsal dinners, birthdays, team banquets, and downtown Carlisle gatherings. Call or send an inquiry and we’ll lock the room.',
  },
  inquiries: [],
}
