import type { MenuItem, SiteData, Tap } from './types'

const tap = (
  n: number,
  name: string,
  style: string,
  brewery: string,
  origin: string,
  abv: number,
  on = true,
): Tap => ({ tap: n, name, style, brewery, origin, abv, on })

const item = (
  partial: Omit<MenuItem, 'available'> & { available?: boolean },
): MenuItem => ({
  available: true,
  ...partial,
})

export const DEFAULT_SITE_DATA: SiteData = {
  venue: {
    name: 'North Hanover Grille',
    shortName: 'N. Hanover Grille',
    phone: '(717) 241-5517',
    phoneHref: 'tel:+17172415517',
    address: '37-39 N. Hanover Street, Carlisle, PA 17013',
    mapsUrl: 'https://goo.gl/maps/Or45R',
    facebookUrl: 'https://www.facebook.com/pages/North-Hanover-Grille/273463392195',
    instagramUrl: 'https://www.instagram.com/n_hanover_grille/',
    timezone: 'America/New_York',
  },
  hours: [
    { day: 0, label: 'Sunday', open: null, close: null },
    { day: 1, label: 'Monday', open: null, close: null },
    { day: 2, label: 'Tuesday', open: '11:00', close: '21:00' },
    { day: 3, label: 'Wednesday', open: '11:00', close: '21:00' },
    { day: 4, label: 'Thursday', open: '11:00', close: '21:00' },
    { day: 5, label: 'Friday', open: '11:00', close: '21:30' },
    { day: 6, label: 'Saturday', open: '11:00', close: '21:30' },
  ],
  taps: [
    tap(1, 'Left Hand Milk Stout', 'Stout', 'Left Hand Brewing', 'Longmont, CO', 6.0),
    tap(2, 'Big Oyster Whale Song', 'Sour', 'Big Oyster Brewery', 'Lewes, DE', 5.0),
    tap(3, 'New Trail Broken Heels', 'IPA', 'New Trail Brewing', 'Williamsport, PA', 7.0),
    tap(4, 'Thomas Hooker #No Filter', 'IPA', 'Thomas Hooker Brewing', 'Bloomfield, CT', 7.0),
    tap(5, 'Yuengling Lager', 'Lager', 'D.G. Yuengling & Son', 'Pottsville, PA', 4.5),
    tap(6, 'Golden Road Mango Cart', 'Wheat', 'Golden Road Brewing', 'Los Angeles, CA', 4.0),
    tap(7, 'Miller Lite', 'Lager', 'Miller Brewing', 'Milwaukee, WI', 4.2),
    tap(8, 'Evergrain Joose Juicy', 'IPA', 'Ever Grain Brewing', 'Camp Hill, PA', 6.0),
    tap(9, 'Carlsberg', 'Lager', 'Carlsberg', 'Copenhagen, Denmark', 5.0),
    tap(10, 'Franziskaner Hefeweizen', 'Hefeweizen', 'Spaten-Franziskaner', 'Munich, Germany', 5.0),
    tap(11, 'Modelo', 'Lager', 'Grupo Modelo', 'Mexico', 4.4),
    tap(12, 'Dewey Swishy Pants IPA', 'IPA', 'Dewey Beer Co.', 'Dewey Beach, DE', 6.5),
    tap(13, 'Downeast Peach Mango Cider', 'Cider', 'Downeast Cider House', 'Boston, MA', 5.0),
    tap(14, "Bell's Two Hearted Ale", 'IPA', "Bell's Brewery", 'Comstock, MI', 7.0),
    tap(15, '', 'Seasonal', 'Open tap', '', 0, false),
    tap(16, '', 'Seasonal', 'Open tap', '', 0, false),
  ],
  sauces: [
    'Honey BBQ',
    'Bourbon Honey BBQ',
    'Wing Dust',
    'Old Bay',
    'Garlic Parmesan',
    'Teriyaki',
    'Mild',
    'Hot',
    'Bourbon Hot',
    'Garlic Hot',
    'Honey Hot',
    'Hot Cajun',
    'Extra Hot',
    'BBQ',
    'Habanero Mango',
    'Garlic',
    'Sweet & Sour',
    'Bourbon Sweet & Sour',
  ],
  wingNotes:
    'Traditional wings served with blue cheese and celery. Tuesday boneless wings 60¢ starting at 3 PM.',
  menu: [
    item({
      id: 'wings-bone-in',
      category: 'wings',
      name: 'Bone-In Wings',
      description: 'Traditional wings with blue cheese and celery.',
      variants: [
        { id: '8', label: '8 pc', price: 11.99 },
        { id: '12', label: '12 pc', price: 15.99 },
        { id: '18', label: '18 pc', price: 21.99 },
      ],
    }),
    item({
      id: 'wings-boneless',
      category: 'wings',
      name: 'Boneless Wings',
      description: 'Tuesday 60¢ starting at 3 PM.',
      tags: ['Tuesday 60¢ from 3 PM'],
      variants: [
        { id: '8', label: '8 pc', price: 10.59 },
        { id: '12', label: '12 pc', price: 12.99 },
        { id: '18', label: '18 pc', price: 16.99 },
      ],
    }),
    item({
      id: 'quesadilla-cheese',
      category: 'quesadillas',
      name: 'Cheese Quesadilla',
      description: 'Simply perfect. Served with salsa and sour cream.',
      variants: [{ id: 'std', label: '', price: 9.59 }],
    }),
    item({
      id: 'quesadilla-chicken',
      category: 'quesadillas',
      name: 'Chicken Quesadilla',
      description: 'Grilled chicken in a cheese quesadilla. Salsa and sour cream.',
      variants: [{ id: 'std', label: '', price: 11.59 }],
    }),
    item({
      id: 'quesadilla-garden',
      category: 'quesadillas',
      name: 'Garden Quesadilla',
      description: 'Sautéed green peppers, mushrooms, onions, tomatoes in a cheese quesadilla.',
      variants: [{ id: 'std', label: '', price: 10.99 }],
    }),
    item({
      id: 'quesadilla-steak',
      category: 'quesadillas',
      name: 'Steak Quesadilla',
      description: 'Shaved sirloin, grilled onions, mushrooms, peppers in a cheese quesadilla.',
      variants: [{ id: 'std', label: '', price: 12.99 }],
    }),
    item({
      id: 'quesadilla-buffalo',
      category: 'quesadillas',
      name: 'Buffalo Quesadilla',
      description: 'Grilled chicken, Honey Hot sauce, and blue cheese.',
      variants: [{ id: 'std', label: '', price: 12.59 }],
    }),
    item({
      id: 'cheese-curds',
      category: 'starters',
      name: 'Cheese Curds',
      description: 'Fried cheese curds served with buttermilk ranch.',
      variants: [{ id: 'std', label: '', price: 6.99 }],
    }),
    item({
      id: 'fat-tire-dip',
      category: 'starters',
      name: 'New Belgium Fat Tire Cheese Dip',
      description: 'With soft pretzels.',
      variants: [{ id: 'std', label: '', price: 9.99 }],
    }),
    item({
      id: 'nachos-grande',
      category: 'starters',
      name: 'Nachos Grande',
      description:
        'Crisp corn chips, lettuce, tomatoes, Monterey Jack Cheddar, our chili, sour cream, salsa and jalapeño peppers.',
      variants: [
        { id: 'std', label: '', price: 11.99 },
        { id: 'brisket', label: 'With Brisket', price: 12.99 },
      ],
    }),
    item({
      id: 'street-corn-dip',
      category: 'starters',
      name: 'Mexican Street Corn Dip',
      description: 'Served with tortilla strips.',
      variants: [{ id: 'std', label: '', price: 8.99 }],
    }),
    item({
      id: 'potato-skins-hanover',
      category: 'starters',
      name: 'Hanover Potato Skins',
      description: 'Monterey Jack Cheddar with bacon bits.',
      variants: [{ id: 'std', label: '', price: 8.59 }],
    }),
    item({
      id: 'potato-skins-texas',
      category: 'starters',
      name: 'Texas Potato Skins',
      description: 'Our homemade chili and Monterey Jack Cheddar.',
      variants: [{ id: 'std', label: '', price: 8.59 }],
    }),
    item({
      id: 'brisket-flatbread',
      category: 'starters',
      name: 'Brisket Flat Bread',
      description: 'Brisket, provolone, sautéed onions, sweet & sour sauce.',
      variants: [{ id: 'std', label: '', price: 14.99 }],
    }),
    item({
      id: 'cbr-flatbread',
      category: 'starters',
      name: 'Chicken Bacon Ranch Flat Bread',
      description: 'Grilled chicken, bacon, provolone, ranch & sweet ’n sour sauce.',
      variants: [{ id: 'std', label: '', price: 14.99 }],
    }),
    item({
      id: 'cheese-fries',
      category: 'starters',
      name: 'Cheese Fries',
      variants: [
        { id: 'std', label: '', price: 8.99 },
        { id: 'bacon', label: 'With Bacon', price: 10.99 },
        { id: 'brisket', label: 'Brisket & Sautéed Onions', price: 13.99 },
      ],
    }),
    item({
      id: 'buffalo-chicken-dip',
      category: 'starters',
      name: 'Buffalo Chicken Dip',
      description: 'Served with a soft pretzel.',
      variants: [{ id: 'std', label: '', price: 10.99 }],
    }),
    item({
      id: 'french-onion',
      category: 'soups-salads',
      group: 'Scratch Soups',
      name: 'French Onion',
      description: 'All our soups are made from scratch, right here.',
      variants: [{ id: 'std', label: '', price: 6.99 }],
    }),
    item({
      id: 'soup-du-jour',
      category: 'soups-salads',
      group: 'Scratch Soups',
      name: 'Soup du Jour',
      variants: [{ id: 'std', label: '', price: 5.59 }],
    }),
    item({
      id: 'nhg-chili',
      category: 'soups-salads',
      group: 'Scratch Soups',
      name: 'NHG Chili',
      description: 'Upon availability.',
      variants: [{ id: 'std', label: '', price: 6.99 }],
    }),
    item({
      id: 'greek-salad',
      category: 'soups-salads',
      group: 'Salads',
      name: 'Greek Salad',
      description:
        'Mixed greens, green pepper, tomato, feta, kalamata olives, Greek dressing.',
      variants: [
        { id: 'std', label: '', price: 12.99 },
        { id: 'chicken', label: 'Chicken', price: 15.99 },
        { id: 'steak', label: 'Steak', price: 16.99 },
        { id: 'shrimp', label: 'Shrimp', price: 16.99 },
        { id: 'salmon', label: 'Fresh Salmon', price: 16.99 },
      ],
    }),
    item({
      id: 'southwest-salad',
      category: 'soups-salads',
      group: 'Salads',
      name: 'SouthWest Salad',
      description:
        'Black bean corn salsa, avocado, avocado poblano ranch, tomato, green pepper, grilled chicken & Monterey Jack Cheddar.',
      variants: [{ id: 'std', label: '', price: 13.99 }],
    }),
    item({
      id: 'caesar',
      category: 'soups-salads',
      group: 'Salads',
      name: 'Caesar Salad',
      description: 'Romaine, croutons, Caesar dressing, Parmesan.',
      variants: [
        { id: 'std', label: '', price: 9.99 },
        { id: 'chicken', label: 'Chicken', price: 14.99 },
        { id: 'shrimp', label: 'Shrimp', price: 16.99 },
        { id: 'steak', label: 'Steak', price: 16.99 },
        { id: 'salmon', label: 'Fresh Salmon', price: 16.99 },
      ],
    }),
    item({
      id: 'blackened-salmon-salad',
      category: 'soups-salads',
      group: 'Salads',
      name: 'Fresh Blackened Salmon Salad',
      description: 'Mixed greens, candied walnuts, feta, onion straws, apple vinaigrette.',
      variants: [{ id: 'std', label: '', price: 14.99 }],
    }),
    item({
      id: 'pittsburgh-salad',
      category: 'soups-salads',
      group: 'Salads',
      name: 'Pittsburgh Salad',
      description: 'Mixed greens topped with french fries and Monterey Jack Cheddar.',
      variants: [
        { id: 'chicken', label: 'Chicken', price: 13.99 },
        { id: 'steak', label: 'Steak', price: 15.99 },
      ],
    }),
    item({
      id: 'wrap-phil',
      category: 'handhelds',
      group: 'Wraps',
      name: 'Phil',
      description:
        'Fried chicken tenders, bacon, ranch, Swiss. Homemade chips & pickle. Sub fries $2.50, soup $3.00.',
      variants: [{ id: 'std', label: '', price: 8.99 }],
    }),
    item({
      id: 'wrap-rampage',
      category: 'handhelds',
      group: 'Wraps',
      name: 'Rampage',
      description: 'Grilled chicken, bacon, grilled onions, American cheese, horseradish Dijon.',
      variants: [{ id: 'std', label: '', price: 8.99 }],
    }),
    item({
      id: 'wrap-club',
      category: 'handhelds',
      group: 'Wraps',
      name: 'Chicken Club',
      description: 'Grilled chicken, bacon, lettuce, tomato, mayo.',
      variants: [{ id: 'std', label: '', price: 8.99 }],
    }),
    item({
      id: 'wrap-western',
      category: 'handhelds',
      group: 'Wraps',
      name: 'Western',
      description: 'Fried chicken tenders, bacon, BBQ, Monterey Jack Cheddar.',
      variants: [{ id: 'std', label: '', price: 8.99 }],
    }),
    item({
      id: 'wrap-buffalo',
      category: 'handhelds',
      group: 'Wraps',
      name: 'Buffalo Wrap',
      description: 'Fried chicken tenders dipped in hot sauce, bleu cheese.',
      variants: [{ id: 'std', label: '', price: 8.99 }],
    }),
    item({
      id: 'wrap-southwest',
      category: 'handhelds',
      group: 'Wraps',
      name: 'SouthWest Wrap',
      description:
        'Grilled chicken, black bean corn salsa, Monterey Jack Cheddar, avocado poblano ranch.',
      variants: [{ id: 'std', label: '', price: 8.99 }],
    }),
    item({
      id: 'burger-brisket',
      category: 'handhelds',
      group: 'Handhelds',
      name: 'Brisket Burger',
      description: '8 oz angus, grilled onions, brisket BBQ, beer cheese sauce.',
      variants: [{ id: 'std', label: '', price: 12.59 }],
    }),
    item({
      id: 'burger-patty-melt',
      category: 'handhelds',
      group: 'Handhelds',
      name: 'Patty Melt',
      description: '6 oz angus on grilled rye, Swiss, grilled onions.',
      variants: [{ id: 'std', label: '', price: 9.99 }],
    }),
    item({
      id: 'sandwich-bbq-chicken-ranch',
      category: 'handhelds',
      group: 'Handhelds',
      name: 'BBQ Chicken Ranch',
      description: 'Grilled chicken, provolone, bacon, BBQ, ranch, lettuce on a roll.',
      variants: [{ id: 'std', label: '', price: 9.99 }],
    }),
    item({
      id: 'burger-alamo',
      category: 'handhelds',
      group: 'Handhelds',
      name: 'Alamo',
      description: '8 oz angus, grilled onions, bacon, BBQ, Monterey Jack Cheddar.',
      variants: [{ id: 'std', label: '', price: 10.99 }],
    }),
    item({
      id: 'cheesesteak',
      category: 'handhelds',
      group: 'Handhelds',
      name: 'Cheesesteak',
      description: 'Shaved sirloin, grilled onions, beer cheese on a sub roll.',
      variants: [{ id: 'std', label: '', price: 9.59 }],
    }),
    item({
      id: 'black-bean-burger',
      category: 'handhelds',
      group: 'Handhelds',
      name: 'Black Bean Burger',
      description: 'Lettuce, tomato, onion, salsa on a roll.',
      variants: [{ id: 'std', label: '', price: 8.99 }],
    }),
    item({
      id: 'crab-cake-sandwich',
      category: 'handhelds',
      group: 'Handhelds',
      name: 'Homemade Crab Cake',
      description: 'Served on a roll with tartar on the side.',
      variants: [{ id: 'std', label: '', price: 15.99 }],
    }),
    item({
      id: 'classic-burger',
      category: 'handhelds',
      group: 'Handhelds',
      name: 'Classic Burger',
      description: '8 oz angus, American cheese, lettuce, tomato, onion, mayo on a roll.',
      variants: [{ id: 'std', label: '', price: 9.99 }],
    }),
    item({
      id: 'salmon-blt',
      category: 'handhelds',
      group: 'Handhelds',
      name: 'Fresh Salmon BLT',
      description: 'Broiled salmon, bacon, lettuce, tomato and mayo on a baguette.',
      variants: [{ id: 'std', label: '', price: 13.99 }],
    }),
    item({
      id: 'avocado-chicken',
      category: 'handhelds',
      group: 'Handhelds',
      name: 'Avocado Chicken',
      description:
        'Grilled chicken, fresh avocado, avocado poblano ranch, Swiss, lettuce, tomato.',
      variants: [{ id: 'std', label: '', price: 10.99 }],
    }),
    item({
      id: 'griller',
      category: 'handhelds',
      group: 'Handhelds',
      name: 'Griller',
      description: 'Grilled chicken, sautéed mushrooms, Swiss, on a roll.',
      variants: [{ id: 'std', label: '', price: 8.99 }],
    }),
    item({
      id: 'dickinson',
      category: 'handhelds',
      group: 'Handhelds',
      name: 'Dickinson',
      description: 'Two 8 oz angus burgers, bacon, American and Monterey Jack Cheddar.',
      variants: [{ id: 'std', label: '', price: 15.99 }],
    }),
    item({
      id: 'hooter',
      category: 'handhelds',
      group: 'Handhelds',
      name: 'Hooter',
      description: 'Grilled chicken, Swiss, bacon, grilled onions on a roll.',
      variants: [{ id: 'std', label: '', price: 9.99 }],
    }),
    item({
      id: 'rachel',
      category: 'handhelds',
      group: 'Handhelds',
      name: 'Rachel',
      description: 'Grilled turkey, coleslaw, Swiss, Thousand Island on rye.',
      variants: [{ id: 'std', label: '', price: 8.99 }],
    }),
    item({
      id: 'entree-crab-cakes',
      category: 'entrees',
      name: 'Crab Cakes',
      description: 'Two house-made broiled crab cakes with two sides. Sub Caesar salad +$1.',
      variants: [{ id: 'std', label: '', price: 28.99 }],
    }),
    item({
      id: 'entree-flat-iron',
      category: 'entrees',
      name: 'Flat Iron',
      description: '8 oz Angus strip steak with two sides.',
      variants: [{ id: 'std', label: '', price: 20.99 }],
    }),
    item({
      id: 'entree-sw-salmon',
      category: 'entrees',
      name: 'Fresh Southwest Salmon',
      description:
        'Broiled fresh salmon with black bean corn salsa, avocado, and avocado poblano ranch.',
      variants: [{ id: 'std', label: '', price: 26.99 }],
    }),
    item({
      id: 'entree-fish-chips',
      category: 'entrees',
      name: 'Fish & Chips',
      description: 'Beer battered haddock served with fries.',
      variants: [{ id: 'std', label: '', price: 14.99 }],
    }),
    item({
      id: 'entree-ny-strip',
      category: 'entrees',
      name: 'NY Strip',
      description: '12 oz Angus strip steak with two sides.',
      variants: [{ id: 'std', label: '', price: 26.99 }],
    }),
    item({
      id: 'entree-alfredo',
      category: 'entrees',
      name: 'Pasta Alfredo',
      description: 'Served with garden salad and garlic bread.',
      variants: [
        { id: 'std', label: '', price: 14.99 },
        { id: 'chicken', label: 'Chicken', price: 18.99 },
        { id: 'steak', label: 'Steak', price: 20.99 },
        { id: 'shrimp', label: 'Shrimp', price: 20.99 },
      ],
    }),
    item({
      id: 'side-garden',
      category: 'sides',
      name: 'Garden Salad',
      variants: [{ id: 'std', label: '', price: 4.59 }],
    }),
    item({
      id: 'side-slaw',
      category: 'sides',
      name: 'Coleslaw',
      variants: [{ id: 'std', label: '', price: 2.59 }],
    }),
    item({
      id: 'side-fries',
      category: 'sides',
      name: 'Fries',
      variants: [{ id: 'std', label: '', price: 3.99 }],
    }),
    item({
      id: 'side-sweet-fries',
      category: 'sides',
      name: 'Sweet Potato Fries',
      variants: [{ id: 'std', label: '', price: 4.99 }],
    }),
    item({
      id: 'side-baked-potato',
      category: 'sides',
      name: 'Baked Potato',
      variants: [{ id: 'std', label: '', price: 2.59 }],
    }),
    item({
      id: 'side-onion-rings',
      category: 'sides',
      name: 'Onion Rings',
      variants: [{ id: 'std', label: '', price: 4.29 }],
    }),
    item({
      id: 'side-applesauce',
      category: 'sides',
      name: 'Apple Sauce',
      variants: [{ id: 'std', label: '', price: 2.59 }],
    }),
    item({
      id: 'side-veggie',
      category: 'sides',
      name: 'Veggie of the Day',
      variants: [{ id: 'std', label: '', price: 2.99 }],
    }),
    item({
      id: 'kids-cheeseburger',
      category: 'kids',
      name: 'Cheeseburger',
      description: 'Children 12 and under. Includes fries and small drink.',
      variants: [{ id: 'std', label: '', price: 6.99 }],
    }),
    item({
      id: 'kids-quesadilla',
      category: 'kids',
      name: 'Cheese Quesadilla',
      description: 'Includes small drink.',
      variants: [{ id: 'std', label: '', price: 6.99 }],
    }),
    item({
      id: 'kids-hamburger',
      category: 'kids',
      name: 'Hamburger',
      description: 'Includes fries and small drink.',
      variants: [{ id: 'std', label: '', price: 6.99 }],
    }),
    item({
      id: 'kids-tenders',
      category: 'kids',
      name: 'Chicken Tenders',
      description: 'Includes fries and small drink.',
      variants: [{ id: 'std', label: '', price: 6.99 }],
    }),
    item({
      id: 'kids-mac-dog',
      category: 'kids',
      name: 'Macaroni & Cheese with Hot Dog',
      description: 'No roll. Includes small drink.',
      variants: [{ id: 'std', label: '', price: 6.99 }],
    }),
  ],
  specials: {
    hasFlyer: false,
    updatedAt: null,
  },
  banquet: {
    capacity: 30,
    blurb:
      'Private parties for up to thirty people in our rear dining area. Call 717-241-5517 and we’ll set the room. Bring your party downtown and see why the Grille has become Central Pennsylvania’s restaurant and ale house.',
  },
  inquiries: [],
}
